version: "3.7"
services:
  # flask_app:
  #   build: './api'
  #   environment:
  #     - REDIS_URL=redis
  #     - REDIS_PORT=6379
  #     - MONGODB_HOST=mongodb
  #     - MONGODB_PORT=27017
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - redis

  # simple_worker:
  #   build: './worker'
  #   user: nobody
  #   depends_on:
  #     - redis
  #     - flask_app
  redis:
    image: 'redis'
    ports:
      - '6379:6379'